# example netlify.toml
[build]
  command = "svelte-kit build"
  functions = "netlify/functions"
  publish = "build"

[context.production]
  command = "npx dotenv-vault@latest pull production .env --dotenvMe $PRODUCTION_DOTENV_IT && npm run build"
